name: builder

on:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: RobotLocomotion/drake-external-examples
          ref: main
          path: ros_ws/src
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: drake drake_cmake_installed drake_cmake_installed_apt drake_ament_cmake_installed
          target-ros2-distro: rolling
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "merge-install": true,
                "cmake-target": "install"
              }
            }
