name: builder

on:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: drake
          target-ros2-distro: rolling
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "cmake-target": [
                  "install"
                ],
                "cmake-args": [
                  "-DCMAKE_PREFIX_PATH=/opt/ros/rolling",
                  "-DAMENT_PREFIX_PATH=/opt/ros/rolling",
                  "-DCMAKE_INSTALL_PREFIX=/opt/ros/rolling",
                  "-DCMAKE_BUILD_TYPE=None"
                ]
              }
            }
      - name: Build cmake example
        run: |
          . /opt/ros/rolling/setup.sh
          git clone https://github.com/RobotLocomotion/drake-external-examples
          cd drake-external-examples/drake_cmake_installed_apt
          cmake --build build
          ctest --test-dir build
